### ISSUE TITLE
Bring Excisting Alfred Snippet

### ISSUE THREAD

**Issue by alwinsamson** [alfredapp/snippet-trigger-email-signatures-workflow#1]
Hi,
Just wondering if it's possible to bring the excisting alfred snippets.

**Comment by vitorgalvao** [comment]
Hello @eleftheriakodikas,

The Workflow works as an example/template. The point is that you edit it to your heart’s content or recreate it yourself according to your needs. It shows how you can use *one* snippet to choose from *multiple* results via a List Filter in the middle. It doesn’t interact with your other snippets, though you can make those expand by—in the List Filter—setting `Arg` to a [`{snippet:}` dynamic placeholder](https://www.alfredapp.com/help/workflows/advanced/placeholders/#snippets).
